### PR TITLE
Floating action button

### PR DESCRIPTION
**Pull request by olafkrueger**
Please take a look at this FloatingActionButton implementation.
To hold the Ripple I'm using a BorderContainer with a cornerRadius inside a mask.
Perhaps this could be done better...

### CODE REVIEW

**Comment by olafkrueger** [comment]
Hi Rui,
I've just forked your repo and added the "FloatingActionButton" files to a new branch.
I also updated the FlexSparkMaterial.mxml.
After this I created a pull request that you could hopefully merge into your dev branch.
Feel free to edit the code or if it's to bad garbage collect it ;-)
Olaf

**Comment by rui-cruz** [comment]
Hi Olaf,

Looks great! The icon could have 2 or 3 implementations, like you did with symbols font, with png image or with fxg vector. But for now, its great to have this, then we can upgrade it :)

**Comment by rui-cruz** [comment]
I notice now that I had to add flatspark.swc to be able to compile, I think we will have to break apart this for size-wise (adds 300k to swf) / reference-wise reasons. Or we copy the AwesomeUtils and embed font, or find a way to keep this as an option somehow. 

Do you agree?

Looks great by the way :) good job

**Comment by olafkrueger** [comment]
> I notice now that I had to add flatspark.swc to be able to compile

Oh sorry, cause I'm always using the current version of Apache Flex I forgot to think about the backward compatibility. Flatspark is part of the SDK since 4.14.0.
If your awesome lib will be part of the SDK in one of the next releases the problem would be solved ;-)

> Or we copy the AwesomeUtils and embed font

If somebody already use min 4.14.0 it would be doubled.

The best way probably is as you suggested to implement various options to add the icon ("symbol font", "raster file" and "fxg"). The "symbol font" option requires 4.14.0 at least.
Until we'll have this you could place a hint that the Floating button requires 4.14.0 for now.
What do you think?

BTW: I've no experiance with "fxg". Is this format still alive and with wich tools it could be created?

> Do you agree?

I'll be agree with all as long as we'll get this cool lib as completely as possible ;-)
I'm already using it in a current project!

Thank you,
Olaf

**Comment by olafkrueger** [comment]
Before thinking about the icon options and if I'll found some more time I'll take a look at the textarea component.

**Comment by rui-cruz** [comment]
> Flatspark is part of the SDK since 4.14.0

Its true, but something most be wrong there.. only with 4.14.1 I can compile, otherwise give's me font parse error. with older sdk's the reference its necessary and works fine.

> BTW: I've no experiance with "fxg". Is this format still alive and with witch tools it could be created?

Well I just love it.. I use a old version of Flash Catalyst to optimise vectors, I use it also to mockup my apps. You can use also Adobe Illustrator cs5, or plugins for Inscape. Fxg inside flex its a SpriteVisualElement, and you can use it on mxml directly like: <assets:MyIcon />

more info: http://help.adobe.com/en_US/flex/using/WSda78ed3a750d6b8f26c150d412357de3591-8000.html#WS6A72DBB6-E49E-465f-BAA8-462440405918

> I'll be agree with all as long as we'll get this cool lib as completely as possible ;-)

Let's do it! :+1:

**Pull request merged**
