### PR TITLE
FloatingActionButton

### PR DESCRIPTION
**Pull request by olafkrueger**
I'd like to provide some files that implements a "FloatingActionButton" but I can't attach any .mxml, .as or .txt files :-(

floatingactionbuttondemo

### CODE REVIEW

**Comment by rui-cruz** [comment]
Hi Olaf,

Thats weird.. I'm not an expert on git, but I think you just have to clone the repo on your computer, make your changes and create a pull-request.

I think I don't have any restrictions..

**Comment by olafkrueger** [comment]
Ok, I'll try to do this one evening this week.
One other issue: I was only able to create a pull request by selecting two different branches.
Cause there're only two brachnes "master" and "silder" in your repo I was not able to place the pull request correctly.
Perhaps it's a good idea to add a "develop" branch to the repo?

**Comment by rui-cruz** [comment]
Sure, I'll add it

2015-10-06 14:31 GMT+01:00 ok-at-github <notifications@github.com>:

**Comment by rui-cruz** [comment]
Sure, I'll add it

**Comment by rui-cruz** [comment]
I added the "develop" branch now, If you want you can create a branch "floating-action" and then I merge it to master.

**Comment by olafkrueger** [comment]
Sounds wise, I'll do this!

**Pull request closed without merging**
